---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamlit-service-account
  namespace: trading-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: trading-system
  name: streamlit-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamlit-role-binding
  namespace: trading-system
subjects:
- kind: ServiceAccount
  name: streamlit-service-account
  namespace: trading-system
roleRef:
  kind: Role
  name: streamlit-role
  apiGroup: rbac.authorization.k8s.io
