apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: streamlit
  sessionAffinity: ClientIP

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-headless
  labels:
    app: streamlit
spec:
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    name: streamlit
  clusterIP: None
  selector:
    app: streamlit