apiVersion: v1
kind: Service
metadata:
  name: trade-manager
  labels:
    app: trade-manager
spec:
  selector:
    app: trade-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: trade-manager-headless
  labels:
    app: trade-manager
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: trade-manager
