apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trade-manager
  labels:
    app: trade-manager
spec:
  serviceName: trade-manager-headless
  replicas: 2  # Primary + 1 backup
  selector:
    matchLabels:
      app: trade-manager
  template:
    metadata:
      labels:
        app: trade-manager
    spec:
      containers:
      - name: trade-manager
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: SERVICE_TYPE
          value: "trade-manager"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_HOST
          value: "redis-primary"  # Connect to primary Redis
        - name: PYTHONPATH
          value: "/app"
        command: ["python"]
        args: ["main.py"]
        livenessProbe:
          exec:
            command:
            - python
            - health_check.py
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - health_check.py
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
